# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-token-indexer
networks:
- id: 5042002
  rpc: https://5042002.rpc.thirdweb.com
  start_block: 37398471
  contracts:
  - name: Factory
    address:
    - 0xAa1D72Afa4a90949246Dc239d8B1E00269D503Bb
    handler: src/EventHandlers.ts
    events:
    - event: TokenCreated(address indexed tokenAddress, string name, string symbol, string ipfsCID)
    - event: Trade(address indexed tokenAddress, address indexed user, uint256 tokenAmount, uint256 usdcAmount, bool isBuy, uint256 timestamp)
unordered_multichain_mode: true
preload_handlers: true
